---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/hoevebouwlust.nl/wp-content/plugins/bwlst-zuivel-verkooplocaties/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp bouwlust-zuivel-verkooplocaties.php "$DEPLOYPATH"
    - /bin/cp -R includes "$DEPLOYPATH"
